// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Bu dosyadaki değerleri kendi Firebase projenizin
/// bilgileriyle değiştirmeniz gerekmektedir.
///
/// Terminalde şu komutu çalıştırarak otomatik oluşturabilirsiniz:
/// ```
/// flutterfire configure
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Aşağıdaki değerleri kendi Firebase projenizin bilgileriyle değiştirin
  // veya `flutterfire configure` komutunu çalıştırın.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw4TCKwie885a_neta_Pzi_jcxJdHHaMo',
    appId: '1:163018685273:android:943f211221737ce7732a48',
    messagingSenderId: '163018685273',
    projectId: 'doktorapp-dental',
    storageBucket: 'doktorapp-dental.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjgkHUr9ejeZoSgTxxrgwSROuCgOAJ1VE',
    appId: '1:163018685273:ios:437915f4181bc9d5732a48',
    messagingSenderId: '163018685273',
    projectId: 'doktorapp-dental',
    storageBucket: 'doktorapp-dental.firebasestorage.app',
    iosBundleId: 'com.example.doktorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.example.doktorapp',
  );
}